import { build } from 'esbuild';
import path from 'node:path';

const shared = {
  bundle: true,
  logLevel: 'info',
  sourcemap: false,
  target: ['es2017'],
};

await build({
  ...shared,
  banner: { js: '/* @generated by npm run build; edit assets/src/frontend instead. */' },
  entryPoints: ['assets/src/frontend/index.js'],
  format: 'iife',
  minify: false,
  outfile: 'assets/js/eit-frontend.js',
});

await build({
  ...shared,
  banner: { js: '/* @generated by npm run build; edit assets/src/editor instead. */' },
  entryPoints: ['assets/src/editor/index.js'],
  format: 'iife',
  minify: false,
  outfile: 'assets/js/eit-editor.js',
});

await build({
  ...shared,
  banner: { css: '/* @generated by npm run build; edit filter-controller modules instead. */' },
  entryPoints: ['assets/src/frontend/index.css'],
  minify: false,
  outfile: 'assets/css/eit-frontend.css',
});

await build({
  ...shared,
  banner: { css: '/* @generated by npm run build; edit assets/src/admin instead. */' },
  entryPoints: ['assets/src/admin/index.css'],
  minify: false,
  outfile: 'assets/css/eit-admin.css',
});

const systemsRoot = path.resolve( 'assets/src/systems' );
const systemsAlias = {
  react: path.join( systemsRoot, 'react-shim.js' ),
  'react-dom': path.join( systemsRoot, 'react-dom-shim.js' ),
  'react/jsx-runtime': path.join( systemsRoot, 'jsx-runtime-shim.js' ),
  '@wordpress/components': path.join( systemsRoot, 'wordpress-components-shim.js' ),
  '@wordpress/data': path.join( systemsRoot, 'wordpress-data-shim.js' ),
  '@wordpress/i18n': path.join( systemsRoot, 'wordpress-i18n-shim.js' ),
};

await build({
  ...shared,
  alias: systemsAlias,
  banner: { js: '/* @generated by npm run build; edit assets/src/systems instead. */' },
  entryPoints: ['assets/src/systems/index.jsx'],
  format: 'iife',
  jsx: 'automatic',
  minify: true,
  legalComments: 'eof',
  outfile: 'assets/js/eit-systems.js',
});

await build({
  ...shared,
  banner: { css: '/* @generated by npm run build; edit assets/src/systems/index.css instead. */' },
  entryPoints: ['assets/src/systems/index.css'],
  minify: true,
  outfile: 'assets/css/eit-systems.css',
});
