import { build } from 'esbuild';

const shared = {
  bundle: true,
  logLevel: 'info',
  sourcemap: false,
  target: ['es2017'],
};

await build({
  ...shared,
  banner: { js: '/* @generated by npm run build; edit assets/src/frontend instead. */' },
  entryPoints: ['assets/src/frontend/index.js'],
  format: 'iife',
  minify: false,
  outfile: 'assets/js/eit-frontend.js',
});

await build({
  ...shared,
  banner: { js: '/* @generated by npm run build; edit assets/src/editor instead. */' },
  entryPoints: ['assets/src/editor/index.js'],
  format: 'iife',
  minify: false,
  outfile: 'assets/js/eit-editor.js',
});

await build({
  ...shared,
  banner: { css: '/* @generated by npm run build; edit filter-controller modules instead. */' },
  entryPoints: ['assets/src/frontend/index.css'],
  minify: false,
  outfile: 'assets/css/eit-frontend.css',
});

await build({
  ...shared,
  banner: { css: '/* @generated by npm run build; edit assets/src/admin instead. */' },
  entryPoints: ['assets/src/admin/index.css'],
  minify: false,
  outfile: 'assets/css/eit-admin.css',
});
